version: '2'

services:
    cfsd-recorder:
        image: lowitz/recorder:v0.0.0
        network_mode: "host"
        volumes:
            - /home/cfsd:/home/cfsd
        command: "recorder --cid=219 --freq=2 --scriptPath=/home/cfsd/scripts/ --recordingsPath=/home/cfsd/recordings/"